run-title: H_LSTM_FINAL_EP8
seed: 42
device: cuda
save-path: ckpts
log-path: logs_final/H_LSTM_FINAL_EP8
save-interval: 1000
resume: true
load-title: H_LSTM_FINAL_EP8
dnd: true
start-episode: 5000
optimizer: rmsprop # {rmsprop, adam}
mode: vanilla # for a3c

task:
  max-length: 250
  num-trials: 6
  num-actions: 2
  num-objects: 1000
  num-episodes: 500
  num-stages: 10

  mode: easy # {easy, hard}
  
  input-dim: 12
  state-len: 17
  obs-len: 8
  obj-offset: 3
  
  fix-reward: 0.2
  obj-reward: 1.0
  min-reward: 0

  map-action:
    -  1
    - -1

agent:
  rnn-type: lstm
  mem-units: 256

  dict-len: 10_000
  dict-key-dim: 10
  dict-kernel: cosine

  n-workers: 8
  share-optim: true
  
  value-loss-weight: 0.4
  entropy-weight: 0.01
  max-grad-norm: 0.
  
  gae-lambda: 1.
  gamma: .91
  lr: 7.5e-4
  weight-decay: 0

  n-step-update: 20 